language: node_js
node_js:
- v5
branches:
  only: master
before_script:
- git config --global user.email "email@denysdovhan.com"
- git config --global user.name "Travis Builder"
- git remote rm origin
- git remote add origin https://denysdovhan:${GH_TOKEN}@github.com/denysdovhan/understandinges6ua.git
script:
- npm run deploy
env:
  global:
    secure: YGdeZcRc7Wvlgo916Vdbc9Oa/3CTUhqQbfjQcTtpGYZSuO3vRqweRdcU0dt4m2HelyDqQ6dTt37TGZrY+zOTEWYX84TfHAgGV5FLU+hR1PhL+h8kvker2lK+TfnU0sOkD/939j5j1Lpe7dqaJODR1cN+UQ1R/IM0DT2oH73kHpmOmjNHrxGMr9AgUOUXaPrErc/qUmmkiLrLd7BH4pjdZcnmh8EhKvF5nd34Q6/+mjYMsO3DALcvh7GJReTjGG6qwiZy6OZbE7voh83+IMxkR0VBMumzEumZSaqdx9oUzDfxDZ8cOGKLTlMNGcloABLiHlurRDbSHO2gy02RcRiHwTgQkPCWL/sHD1/t12BgdGK+nUv+8IWyK0br6dw6sbBTStu/X5w9uEkKSPElfU5Otdmuc/hEt0aX5NwfrKYJy4W1K7F9zZs3At8DXJoy1G1oQghwr1C45xKXLt3Ztp4TSmHj+hpxyVNSXmahU9Mj00O0jUWot19apBtLf8BXr76ZtXktOJh3ubOEgoORpM762s3Xk0iYf5lFOUhrtTm7MAD6QqmG5fTMPNMT/BLlzxIWeK1LfXv64llVXAeVHSJ6raIDfJXUdV4MtNqgPapTy2ZkDtQ08OcvD2JFzZlqr5KL4bo5rLURbAlctsG9mn1nx/ElDCbQ+hwq1jyNNNCqG14=
